feat(redis): 自愈支持范围 #3145
TencentBlueKing/blueking-dbm pull request #3146
Opened 2024-01-22 07:23 UTC by xiepaup

2024-01-22 07:34 UTC, lukemakeit approved these changes

2024-01-23 01:55 UTC, zhangzhw8 requested changes

2024-01-23 01:55 UTC, zhangzhw8 commented on dbm-ui/backend/db_services/redis/autofix/bill.py
> +        if cluster.cluster_type not in [
这种cluster_type的判断，统一放到 backend/db_services/redis/util.py 这个文件下吧

2024-01-29 02:51 UTC, xiepaup commented on dbm-ui/backend/db_services/redis/autofix/bill.py
> +        if cluster.cluster_type not in [
done

2024-01-29 03:10 UTC, zhangzhw8 approved these changes

2024-01-29 03:11 UTC, merged