refactor(backend): 集群列表的访问入口支持多域名返回 #5013
TencentBlueKing/blueking-dbm pull request #5023
Opened 2024-06-18 08:13 UTC by Maxwell-416258

2024-06-18 08:13 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/blueking-dbm?pullRequest=5023) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/blueking-dbm?pullRequest=5023) before we can accept your contribution.<br/><hr/>**leifxu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/blueking-dbm?pullRequest=5023) it.</sub>

2024-06-18 10:04 UTC, zhangzhw8 commented on dbm-ui/backend/db_meta/models/cluster_entry.py
> +            elif entry.role == "slave_entry":
"slave_entry" -> ClusterEntryRole.SLAVE_ENTRY

2024-06-18 10:07 UTC, zhangzhw8 requested changes
1. 这个字段所有集群都有，因此不要在每个 resouces 里面添加，而是在 base 里面统一添加2. 现在这个实现方式，会导致 n+1 查询，不要在 to_cluster_representation 里加这里逻辑，改成在列表返回中统一添加

2024-06-19 01:58 UTC, Maxwell-416258 commented on dbm-ui/backend/db_meta/models/cluster_entry.py
> +            elif entry.role == "slave_entry":
好的，已改正

2024-06-19 02:42 UTC, iSecloud commented on dbm-ui/backend/db_services/dbbase/resources/query.py
> +                    {"cluster_entry_type": entry.cluster_entry_type, "entry": entry.entry} for entry in cluster.entries
这个加上entry的角色吧，这样前端才能知道哪些是主域名，哪些是从域名

2024-06-19 02:56 UTC, Maxwell-416258 commented on dbm-ui/backend/db_services/dbbase/resources/query.py
> +                    {"cluster_entry_type": entry.cluster_entry_type, "entry": entry.entry} for entry in cluster.entries
已改

2024-06-19 03:29 UTC, zhangzhw8 approved these changes

2024-06-19 03:29 UTC, zhangzhw8 approved these changes

2024-06-19 03:30 UTC, merged